### PR TITLE
Update mesh.adoc getID

### PR DESCRIPTION
**Pull request by quazi-irfan**

### CODE REVIEW

**Review by mitm001 — COMMENTED** [review]
This method is supposed to be used for internal use only. Why do you feel this change needs to be made?

**Comment by quazi-irfan** [comment]
I didn't know that it's for internal use. Probably it should say that instead?

From the documentation it sounded like end user can/should manually set ID. I played with it, and by default it gave me -1, and I thought it's worth mentioning.

**Comment by mitm001** [comment]
getId()  
Returns the mesh's VAO ID. Internal use only.

I think what's happened is this page needs updating because it looks like mesh has been changed since it was written.
setLineWidth(1)
setPointSize(float pointSize)  
are deprecated but mentioned.

The wiki page should also have a link to the javadoc.
http://javadoc.jmonkeyengine.org/com/jme3/scene/Mesh.html

Do you want to update it? If not, I will eventually.

**Comment by mitm001** [comment]
Looks like I missed updating some sample code in the https://jmonkeyengine.github.io/wiki/jme3/advanced/custom_meshes.html
that uses deprecated stuff.
I have already updated the other pages so these are all that need minor changes.

**Comment by quazi-irfan** [comment]
> Do you want to update it?
Yes, I want to contribute.

In https://jmonkeyengine.github.io/wiki/jme3/advanced/mesh.html, in the Mesh Properties table, I will remove the row containing setLineWidth(1) and setPointSize(4.0f)

In https://jmonkeyengine.github.io/wiki/jme3/advanced/custom_meshes.html, in the Example: Point Mode, I will remove mesh.setPointSize(10f); statement.

Did I miss anything else?

**Comment by mitm001** [comment]
You got it right.

What do you think about adding some links to improve it even more?

Maybe a link under the Vertex Buffer heading pointing to http://javadoc.jmonkeyengine.org/com/jme3/scene/VertexBuffer.Type.html

A link under Mesh Properties heading pointing to
http://javadoc.jmonkeyengine.org/com/jme3/scene/Mesh.html

A link under Mesh Rendering heading pointing to
http://javadoc.jmonkeyengine.org/com/jme3/scene/Mesh.Mode.html

Edit: Maybe just change com.jme3.scene.Mesh in the first paragraph to a link to http://javadoc.jmonkeyengine.org/com/jme3/scene/Mesh.html

rather than three links since all can be accessed from Mesh.html.

**Comment by quazi-irfan** [comment]
I was reading your comment from top to bottom and making the changes only to find out at the end that three links aren't necessary. haha

Should I revert getID() to what it was?

**Comment by mitm001** [comment]
Yes revert getID

**Review by mitm001 — APPROVED** [review]
Thanks for the update.

**Review by mitm001 — APPROVED** [review]

**Comment by mitm001** [comment]
Maybe just add  , for internal use only.

        
Should I revert getID() to what it was?—

**Comment by empirephoenix** [comment]
If i follow the callstack to getId from setID, there is noone calling it. Can anyone validate this? Maybee it should be removed all together then. Also why was it commented out?
https://github.com/jMonkeyEngine/jmonkeyengine/blob/1eb894111ab03e62a0e1319c667ef27a3691a1df/jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java
//        if (ctxCaps.GL_ARB_vertex_array_object){
//            renderMeshVertexArray(mesh, lod, count);
//        }else{
        renderMeshDefault(mesh, lod, count, instanceData);
//        }

**Comment by quazi-irfan** [comment]
> Maybe just add  , for internal use only.
Since you merged this pull request already, do I have to create a new one for it?

**Comment by empirephoenix** [comment]
Yes, once merged the pull request is effectively one usable for discussion and revert anymore.
Still I would like to find out if that stuff is even necessary anymore, at least the current renderer never even sets the id. Maybe that whole thing can either be fixed to be actually used, or thrown out.
@shadowislord Can you maybe give some insight here? As you last worked at that part?

**Comment by mitm001** [comment]
As empire said, yes.

**Comment by mitm001** [comment]
Empire, maybe ask on the forum also.

I think his forum name is Momoko_Fan .

**Pull request merged**
