### PR TITLE
Create .travis.yml

### PR DESCRIPTION
**Pull request by mitm001**
Try to fix exception for missing travis file.
Build config file is required via repository settings, but config is empty.

### CODE REVIEW

**Comment by mitm001** [comment]
Doesn't work as expected.

**Comment by davidB** [comment]
I don't know why/how you remove the original .travis.yml.
I guess you could find it into the git history, else this is the copy, I've found localy:
```
language: java
jdk:
  - oraclejdk8
#  blacklist
branches:
  except:
    - gh-pages
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
   - ./gradlew clean asciidoc
after_success:
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && ./deploy_ghpages.sh'
```

**Comment by mitm001** [comment]
It wasn't removed. What your probably seeing is that I am attempting to add a .travis.yml file to the gh-page branch and that was removed after the travis auto build. It was not setuo in the config for it to be there so it gets removed. There is a problem with setup because a travil.yml file is required to be present on all active branches but the gh-pages branch doesn't have one. See here,https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches See here for the errors its spitting out,https://travis-ci.org/jMonkeyEngine/wiki/requests

**Comment by davidB** [comment]
as said in the docs:
> By default, the gh-pages branch is not built unless you add it to the safelist.

and gh-pages is included in the backlist.

anyways if you want to add .travis.yml into gh-pages, I suggest you to modify ./deploy_ghpages.sh to copy .travis.yml from root.

EDIT: I don't understand the error. Including the default behavior and the settings checked "Build only if .travis.yml is present"

EDIT2: The error are on the branch mitm001-patch-1 (see https://travis-ci.org/jMonkeyEngine/wiki/branches), I don't why travis try to run "ant test" (see https://travis-ci.org/jMonkeyEngine/wiki/builds/297044603)

**Comment by mitm001** [comment]
"By default, the gh-pages branch is not built unless you add it to the safelist." 

Correct but heres the problem,Note that for historical reasons .travis.yml needs to be present on all active branches of your project.https://github.com/jMonkeyEngine/wiki/branches/active If we do the ./deploy_ghpages.sh route then every commit your going to get a email about deleting the travis file it looks like. 

Assuming I read this correctly, 
rm -Rf gh-pages 

I don't know *nix enough to leave everything but that single file. Do you have any input on how to do it properly?

**Comment by mitm001** [comment]
> EDIT: I don't understand the error. Including the default behavior and the settings checked "Build only if .travis.yml is present"

This all revolves around this exception being thrown after every commit. This all started because a couple commits failed for no reason so I started digging around to see why and that's when I discovered this double build situation. Every commit triggers another build. I see there are 2 gh-pages branches but I don't know if that's how GitHub does things or not.

https://github.com/jMonkeyEngine/wiki/branches

When I asked the travis people about this exception all they say is config is wrong. The docs say all active branches have to have travis page, and web searches all came back with same answer, missing travis on gh-pages branch. Even if it does nothing.

Maybe this is what causing the problem since it does show as an active branch?

> EDIT2:The error are on the branch mitm001-patch-1 (see https://travis-ci.org/jMonkeyEngine/wiki/branches), I don't why travis try to run "ant test" (see https://travis-ci.org/jMonkeyEngine/wiki/builds/297044603)

The stale branches #938 was caused by travis needing a language attribute and I just tossed in java to see what happened and it barfed when it found no build.xml. I first sent it through without the attribute and it failed with ruby revert due to ruby being the default language and my not setting rvm attribute. The gh-pages travis file is actually read during the current build process for some reason if it exists in the active gh-pages branch.

None of this is for the master branch. Just experimenting on the gh-branch so no worries. 

I only tested an attribute change on master by setting 

```
except:
- gh-pages

to 

only:
 - master
```

and it had no error or effect so reverted.

**Pull request closed without merging**
