### PR TITLE
Document Blender to JME via glTF

### PR DESCRIPTION
**Pull request by sprinter-17**
Adding a file that summarises information I have discovered in using glTF as an export/import format for models in Blender.

### CODE REVIEW

**Comment by mitm001** [comment]
I am ok with this what about you @Ali-RS?

It can use some refinement with proper explanation of how the reader can actually accomplish the described actions in blender, sdk and or a game with code examples, keyboard/mouse selections and images but its a good start for now.

I haven't tried 2.8 yet but when I do I will be pounding on gltf so I can then offer more detailed suggestions or edit to include some things later.

**Comment by Ali-RS** [comment]
@sprinter-17 thanks for your contribution. 

In the ShapeKeys section, we should mention that they are supported in JME 3.3 only. 
In the Animation section, part 3 is not clear for me.

**Comment by Ali-RS** [comment]
Also, it will be nice to mention in the Animation section, that loading Gltf models using JME 3.3 will automatically load animations with the new animation system introduced in JME 3.3. You can link to this page https://hub.jmonkeyengine.org/t/monkanim-v2/39877 for more info about the new animation system or if you are interested you can create a new page for it in the wiki.

**Comment by sprinter-17** [comment]
@Ali-RS Ok I'll add the JME3.3 comment and link. I'll also add some further details on how to perform the various adjustments in Blender.

If I can work out a neat way of showing the node structure on import I'll do that as well: honestly that was the area that took me the most time to understand so I think a diagram and some code would help there.

I'll make those changes and resubmit in a few days.

**Comment by sprinter-17** [comment]
> @sprinter-17 thanks for your contribution.
> 
> In the ShapeKeys section, we should mention that they are supported in JME 3.3 only.
> In the Animation section, part 3 is not clear for me.

When you refer to 'part 3' of the animation section - do you mean the comment about the active animation being linked under the object? I can reword this or delete if it's not helpful - I really just included it because it confused me that the last edited animation ended up there. But perhaps with the sample structure included this isn't necessary.

**Comment by mitm001** [comment]
This,

> A (potentially) confusing aspect of the export is that all animation actions will be children of the armature node, not the object node. However the action currently being tweaked will be linked under the object node. If you add the object node after import to the jME scene (e.g. by using `getChild` to find it by name) then the only available animation will be the one that is active when the export occurs. To solve this problem make sure you search for and add the parent armature node.

I think he means this is a great spot to explain that Actions are under Anim Control which is a child of the Armature node. Armature is just a name for the node which is a child of the parent node Scene. 

Other importers have different file trees, for example, ogre names the parent node filename-ogremesh and Anim Control, Skeleton Control, etc are all children of the parent node rather than a child node such as Armature. So explaining the difference and what you mean by adding an object node after import will clear things up.

You can link to the sdk for exploring the scene graph by use of the Scene Explorer https://wiki.jmonkeyengine.org/sdk/scene_explorer.html or by traversing the scene graph . https://wiki.jmonkeyengine.org/jme3/advanced/traverse_scenegraph.html for example.

**Comment by mitm001** [comment]
I should add, I am not familiar with the behavior you talk about though where only the last animation is playable so maybe you could explain why that happens. 

Maybe its something you are doing in blender thats causing this? 

Like maybe there is an action selected in the action editor when exporting? 

I wont know until I start back modeling with 2.8 so I cant offer much insight on this part.

**Comment by sprinter-17** [comment]
> I should add, I am not familiar with the behavior you talk about though where only the last animation is playable so maybe you could explain why that happens.
> 
> Maybe its something you are doing in blender thats causing this?
> 
> Like maybe there is an action selected in the action editor when exporting?
> 
> I wont know until I start back modeling with 2.8 so I cant offer much insight on this part.

I've updated that section to try to make it clearer. One of the reasons I added that comment is that in the forum discussion with nehon when he first developed the loader there were several commenters who asked why only 1 animation was being loaded. I suspect it was exactly this problem they were all experiencing: they were playing animations in the object node rather than the parent armature node. Nehon kept referring them to bugs in the Blender glTF exporter which I believe was misleading: I suspect their export was fine it was just that they were looking at the wrong node. 

I also included an example export and import structure in the updated document that I hope will make it clearer and will now add a reference to the SDK (I've never used the SDK so I'll just  use your words in the reference).

**Comment by mitm001** [comment]
@Ali-RS what ya think? 

Still could use some minor tweaks but I think ok myself, gives something that can be edited. 

Once I start using 2.8 I will be able to make some suggestions or make some changes myself. 2.79 was a total bust for me on gltf so my experience is with the broken exporter, not this new version.

**Comment by Ali-RS** [comment]
Looks good to me, and yep we can update it later as new tips/suggestions coming.
@mitm001 please feel free to merge it.

**Comment by Ali-RS** [comment]
@mitm001 for upcoming PR's please use the “squash and merge” option to merge them, this is suggested by JME [CONTRIBUTING](https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/CONTRIBUTING.md#customs-around-integration-branching-tagging-and-releases) doc.
Thanks

**Comment by davidB** [comment]
you can configure the default choice for the merge button into the settings of the project (my favorite and default is "rebase and merge" to have a linear history).

**Comment by mitm001** [comment]
I use the github web interface for merge so are you positive I should do rebase and merge?

Both of those options will screw everything up and create a dirty history when squash and merge or rebase and merge from a fork so I went with merge because I was not sure about the other two even though I am doing it here as a collaborator.

See this link,
https://github.community/t5/How-to-use-Git-and-GitHub/Update-fork-from-web-interface/td-p/25462

I use rebase and merge from netbeans to my own repos but there I am doing it locally and from branches,.

**Comment by mitm001** [comment]
This pr isn't showing up. It failed on jdk8. Should I revert it and try a squash and merge?

**Comment by mitm001** [comment]
To clarify, blender_gltf.adoc is in the [master branch](https://github.com/jMonkeyEngine/wiki/tree/master/src/docs/asciidoc/jme3/advanced), but the html isnt in the [gh-pages](https://github.com/jMonkeyEngine/wiki/tree/gh-pages/jme3/advanced) branch.

**Comment by davidB** [comment]
It's because they're a build error, merge the PR openjk11 or openjdk8 that
should fixe the error and rettigger the ci including update of gh-pages

**Comment by Ali-RS** [comment]
Fixed now.

**Pull request merged**
