### PR TITLE
Switch to openjdk8 build

### PR DESCRIPTION
**Pull request by Ali-RS**
Testing openjdk8 build...

Possible fix for #99

### CODE REVIEW

**Comment by mitm001** [comment]
Worked with openjdk8 Java. openjdk11 may of failed due to gradle wrapper?

https://stackoverflow.com/questions/54507225/intellij-gradle-could-not-determine-java-version-from-11-0-1

**Comment by mitm001** [comment]
See:

https://github.com/jMonkeyEngine/wiki/blob/master/gradle/wrapper/gradle-wrapper.properties

https://stackoverflow.com/questions/54125462/how-to-fix-failure-build-failed-with-an-exception-could-not-determine-java-v

**Comment by mitm001** [comment]
@Ali-RS this shows to me as not merged yet using the web interface. What do you see? If you are seeing the same thing I would merge this one first or close it and then do 100 so it moves to openjdk11.

**Comment by Ali-RS** [comment]
Yes, let's close this and go with openjdk11.

**Pull request closed without merging**
